[build]
  command = "npm run build"
  publish = "public"  # Serves index.html as the main landing page

[[redirects]]
  from = "/react"
  to = "/react-stock-tracker/build/index.html"
  status = 200

[[redirects]]
  from = "/angular"
  to = "/angular-stock-tracker/dist/angular-stock-tracker/index.html"
  status = 200